version: "3.7"

services:
  sport_house_api_django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: sport_house_api_django
    volumes:
      - .:/app:z
#      - static_volume:/app/django_static
#      - media_volume:/app/media
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
    ports:
      - 8000:8000
      - 5678:5678
    command: /start

  redis:
    image: redis:5.0
    container_name: redis

  celeryworker:
    <<: *django
    image: sport_house_api_celeryworker
    container_name: celeryworker
    depends_on:
      - redis
    ports: [ ]
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: sport_house_api_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
    ports: [ ]
    command: /start-celerybeat

  flower:
    <<: *django
    image: sport_house_api_flower
    container_name: flower
    command: /start-flower
    ports:
      - 5557:5555
    depends_on:
      - redis
      - celerybeat
      - celeryworker

#volumes:
#    static_volume: {}
#    media_volume: {}