# Generated by Django 4.1 on 2022-09-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_sporttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhysicalTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "index",
                    models.IntegerField(unique=True, verbose_name="Индекс (для ИИ)"),
                ),
            ],
            options={
                "verbose_name": "(Справочник) Вид физической подготовки",
                "verbose_name_plural": "(Справочник) Виды физической подготовки",
            },
        ),
    ]
