# Generated by Django 4.0.7 on 2022-09-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_physicaltraining'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportTypeСontraindication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Спорт')),
                ('index', models.IntegerField(unique=True, verbose_name='Индекс спорта (для ИИ)')),
            ],
            options={
                'verbose_name': '(Справочник) Вид спорта - для противопоказаний',
                'verbose_name_plural': '(Справочник) Виды спорта - для противопоказаний',
            },
        ),
    ]
