# Generated by Django 4.0.7 on 2022-10-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_sporttypeсontraindication'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporttype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='sporttypeсontraindication',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
