# Generated by Django 4.0.7 on 2022-10-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_sporttype_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип уведомления')),
            ],
            options={
                'verbose_name': '(Справочник) Тип уведомления',
                'verbose_name_plural': '(Справочник) Типы уведомлений',
            },
        ),
    ]
