# Generated by Django 4.0.7 on 2022-11-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_locationcategory_locationsporttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCoating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': '(Справочник) Вид покрытия на спортивной площадке',
                'verbose_name_plural': '(Справочник) Виды покрытия на спортивных площадках',
            },
        ),
        migrations.CreateModel(
            name='LocationLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': '(Справочник) Вид освещения на спортивной площадке',
                'verbose_name_plural': '(Справочник) Виды освещения на спортивных площадках',
            },
        ),
        migrations.AlterModelOptions(
            name='locationsporttype',
            options={'verbose_name': '(Справочник) Категория спорта на спортивной площадке', 'verbose_name_plural': '(Справочник) Категории спорта спортивных площадок'},
        ),
    ]
