# Generated by Django 4.0.7 on 2022-11-30 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0011_eventlocationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': '(Справочник) Тип модели обучения',
                'verbose_name_plural': '(Справочник) Типы модели обучения',
            },
        ),
        migrations.CreateModel(
            name='OrderRecomendationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(verbose_name='Слаг поля')),
                ('order_num', models.PositiveIntegerField(unique=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': '(Справочник) Порядок входных полей',
                'verbose_name_plural': '(Справочник) Порядок входных полей',
            },
        ),
        migrations.CreateModel(
            name='FileRecomendationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активная модель')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.file', verbose_name='Файл модели')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai.modeltype', verbose_name='Тип модели')),
            ],
            options={
                'verbose_name': '(Справочник) Модель обучения',
                'verbose_name_plural': '(Справочник) Модели обучения',
            },
        ),
    ]
