# Generated by Django 4.1 on 2022-08-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_locationcategory_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locationcategory",
            name="slug",
        ),
    ]
