# Generated by Django 4.1 on 2022-08-26 18:51

import apps.location.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0005_locationsporttype_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=apps.location.models.get_file_path_location_image,
                verbose_name="Иконка категории",
            ),
        ),
    ]
