# Generated by Django 4.1 on 2022-08-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0005_locationsporttype_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="image",
            field=models.ImageField(
                null=True,
                verbose_name="Иконка категории",
            ),
        ),
    ]
