# Generated by Django 4.0.7 on 2022-10-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_remove_location_direction_remove_location_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=510, null=True, verbose_name='Наименование'),
        ),
    ]
