# Generated by Django 4.0.7 on 2022-10-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_alter_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('sub_thoroughfare', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер дома/строения')),
                ('sub_locality', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Индекс')),
                ('administrative_area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Область')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('sub_administrative_area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Округ')),
                ('thoroughfare', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('country_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код страны')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Полный адрес (Улица и дом)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': '(Справочник) Адрес',
                'verbose_name_plural': '(Справочник) Адреса',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='additional_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Доп. электронный адрес площадки'),
        ),
        migrations.AddField(
            model_name='location',
            name='additional_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Доп. номер телефона'),
        ),
        migrations.AddField(
            model_name='location',
            name='confirmed_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона для подтверждения площадки'),
        ),
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронный адрес площадки'),
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
