# Generated by Django 4.0.7 on 2022-10-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_locationaddress_location_additional_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTimeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_name', models.CharField(max_length=255, verbose_name='День Недели')),
                ('start_date', models.DateTimeField(verbose_name='Начало работы')),
                ('end_date', models.DateTimeField(verbose_name='Завершение работы')),
            ],
            options={
                'verbose_name': 'Время работы спортивной площадки',
                'verbose_name_plural': 'Время работы спортивной площадки',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='work_time',
            field=models.ManyToManyField(to='location.worktimelocation', verbose_name='Время работы'),
        ),
    ]
