# Generated by Django 4.0.7 on 2022-10-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_location_address_location_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
