# Generated by Django 4.0.7 on 2022-10-18 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0013_location_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('commentary', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.status', verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус площадки',
                'verbose_name_plural': 'Статус площадки',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='status_list',
            field=models.ManyToManyField(to='location.locationstatus', verbose_name='Статусы локации'),
        ),
    ]
