# Generated by Django 4.0.7 on 2022-11-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_remove_user_my_location'),
        ('location', '0014_locationstatus_location_status_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='LocationCategory',
        ),
        migrations.DeleteModel(
            name='LocationSportType',
        ),
    ]
