# Generated by Django 4.0.7 on 2022-11-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_alter_worktimelocation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Блокировка'),
        ),
    ]
