# Generated by Django 4.0.7 on 2023-01-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0021_remove_location_sport_type1_location_sport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimelocation',
            name='breaking',
            field=models.PositiveIntegerField(default=10, verbose_name='Перерыв'),
        ),
        migrations.AddField(
            model_name='worktimelocation',
            name='interval',
            field=models.PositiveIntegerField(default=60, verbose_name='Интервал'),
        ),
    ]
