# Generated by Django 4.0.7 on 2023-01-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0022_worktimelocation_breaking_worktimelocation_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktimelocation',
            name='breaking',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Перерыв'),
        ),
        migrations.AlterField(
            model_name='worktimelocation',
            name='interval',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Интервал'),
        ),
    ]
