# Generated by Django 4.0.7 on 2023-01-19 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0023_alter_worktimelocation_breaking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('start_event', models.TimeField(verbose_name='Время начала')),
                ('end_event', models.TimeField(verbose_name='Время завершения')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_event', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('members', models.ManyToManyField(related_name='user_member_booking', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Бронирование площадки',
                'verbose_name_plural': 'Бронирования площадки',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='bookings',
            field=models.ManyToManyField(to='location.bookinglocation', verbose_name='Бронирования'),
        ),
    ]
