# Generated by Django 4.0.7 on 2023-01-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0024_bookinglocation_location_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglocation',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
