# Generated by Django 4.0.7 on 2023-01-23 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_eventlocationtype'),
        ('location', '0025_bookinglocation_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListBookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('commentary', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Статусы бронирований',
                'verbose_name_plural': 'Статусы бронирований',
            },
        ),
        migrations.AddField(
            model_name='bookinglocation',
            name='statuses',
            field=models.ManyToManyField(through='location.ListBookingStatus', to='base.status', verbose_name='Cтатусы'),
        ),
        migrations.AddField(
            model_name='listbookingstatus',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listbookingstatus', to='location.bookinglocation', verbose_name='Бронирование'),
        ),
        migrations.AddField(
            model_name='listbookingstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='listbookingstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
