# Generated by Django 4.0.7 on 2023-01-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0026_listbookingstatus_bookinglocation_statuses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='web_site',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Веб сайт площадки'),
        ),
    ]
