# Generated by Django 4.0.2 on 2022-08-11 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReccomendationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=8, verbose_name='Пол')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес')),
                ('height', models.PositiveIntegerField(verbose_name='Рост')),
                ('physical_training', models.CharField(max_length=255, verbose_name='Физическая подготовка')),
                ('meat', models.BooleanField(verbose_name='Мясо')),
                ('fish', models.BooleanField(verbose_name='Рыба')),
                ('milk', models.BooleanField(verbose_name='Молочные продукты')),
                ('egg', models.BooleanField(verbose_name='Яйца')),
                ('allergy_citrus', models.BooleanField(verbose_name='Аллергия (цитрусовые)')),
                ('allergy_nut', models.BooleanField(verbose_name='Аллергия (орехи)')),
                ('allergy_honey', models.BooleanField(verbose_name='Аллергия (мед)')),
                ('musculoskeletal_system', models.BooleanField(verbose_name='Заболевание(Опорно-двигательный аппарат)')),
                ('diabetes', models.BooleanField(verbose_name='Заболевание(Диабет)')),
                ('health', models.BooleanField(verbose_name='Заболевание(Сердечно-сосудистые)')),
                ('varicose', models.BooleanField(verbose_name='Заболевание(Варикозное расширение вен)')),
                ('epilepsy', models.BooleanField(verbose_name='Заболевание(Эпилепсия)')),
                ('myopia', models.BooleanField(verbose_name='Заболевание(Близорукость)')),
                ('breath', models.BooleanField(verbose_name='Заболевание(Органы дыхания)')),
                ('digestion', models.BooleanField(verbose_name='Заболевание(Органы пищеварения)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Входные данные рекомендаций',
                'verbose_name_plural': 'Входные данные рекомендаций',
            },
        ),
    ]
