# Generated by Django 4.0.2 on 2022-08-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userreccomendationinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='allergy_citrus',
            field=models.BooleanField(blank=True, null=True, verbose_name='Аллергия (цитрусовые)'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='allergy_honey',
            field=models.BooleanField(blank=True, null=True, verbose_name='Аллергия (мед)'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='allergy_nut',
            field=models.BooleanField(blank=True, null=True, verbose_name='Аллергия (орехи)'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='breath',
            field=models.BooleanField(blank=True, null=True, verbose_name='Заболевание(Органы дыхания)'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='diabetes',
            field=models.BooleanField(blank=True, null=True, verbose_name='Заболевание(Диабет)'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='digestion',
            field=models.BooleanField(blank=True, null=True, verbose_name='Заболевание(Органы пищеварения)'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='egg',
            field=models.BooleanField(blank=True, null=True, verbose_name='Яйца'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='epilepsy',
            field=models.BooleanField(blank=True, null=True, verbose_name='Заболевание(Эпилепсия)'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='fish',
            field=models.BooleanField(blank=True, null=True, verbose_name='Рыба'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='health',
            field=models.BooleanField(blank=True, null=True, verbose_name='Заболевание(Сердечно-сосудистые)'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='meat',
            field=models.BooleanField(blank=True, null=True, verbose_name='Мясо'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='milk',
            field=models.BooleanField(blank=True, null=True, verbose_name='Молочные продукты'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='musculoskeletal_system',
            field=models.BooleanField(blank=True, null=True, verbose_name='Заболевание(Опорно-двигательный аппарат)'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='myopia',
            field=models.BooleanField(blank=True, null=True, verbose_name='Заболевание(Близорукость)'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='physical_training',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Физическая подготовка'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='varicose',
            field=models.BooleanField(blank=True, null=True, verbose_name='Заболевание(Варикозное расширение вен)'),
        ),
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес'),
        ),
    ]
