# Generated by Django 4.0.2 on 2022-08-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userreccomendationinfo_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreccomendationinfo',
            name='notification_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен для Push уведомлений'),
        ),
    ]
