# Generated by Django 4.0.2 on 2022-08-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userreccomendationinfo_notification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreccomendationinfo',
            name='notification_token',
        ),
        migrations.AddField(
            model_name='user',
            name='notification_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен для Push уведомлений'),
        ),
    ]
