# Generated by Django 4.0.2 on 2022-08-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_userreccomendationinfo_notification_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Выходные данные рекомендаций',
                'verbose_name_plural': 'Выходные данные рекомендаций',
            },
        ),
    ]
