# Generated by Django 4.0.2 on 2022-08-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommendation',
            field=models.ManyToManyField(to='user.UserRecommendation', verbose_name='Мои Рекомендации'),
        ),
    ]
