# Generated by Django 4.0.2 on 2022-08-17 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок уведомления')),
                ('body', models.CharField(max_length=255, verbose_name='Тело уведомления')),
                ('delivered', models.BooleanField(default=None, null=True, verbose_name='Статус доставки уведомления')),
                ('delivered_message', models.TextField(blank=True, null=True, verbose_name='Текст сообщения об ошибке доставки')),
                ('notification_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор уведомления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано ли уведомление')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('read_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пуш - уведомление пользователя',
                'verbose_name_plural': 'Пуш - уведомления пользователей',
            },
        ),
    ]
