# Generated by Django 4.0.2 on 2022-08-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_usernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='user_notification',
            field=models.ManyToManyField(to='user.UserNotification', verbose_name='Пуш-уведомления'),
        ),
    ]
