# Generated by Django 4.1 on 2022-08-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0005_locationsporttype_icon"),
        ("user", "0010_remove_usernotification_user_user_user_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotification",
            name="my_location",
            field=models.ManyToManyField(
                to="location.location", verbose_name="Мои площадки"
            ),
        ),
    ]
