# Generated by Django 4.1 on 2022-08-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0005_locationsporttype_icon"),
        ("user", "0011_usernotification_my_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usernotification",
            name="my_location",
        ),
        migrations.AddField(
            model_name="user",
            name="my_location",
            field=models.ManyToManyField(
                to="location.location", verbose_name="Мои площадки"
            ),
        ),
    ]
