# Generated by Django 4.1 on 2022-08-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_sporttype"),
        ("user", "0012_remove_usernotification_my_location_user_my_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrecommendation",
            name="sport",
            field=models.ManyToManyField(
                to="base.sporttype", verbose_name="Рекомендации по видам спорта"
            ),
        ),
    ]
