# Generated by Django 4.0.7 on 2022-09-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_sporttypeсontraindication'),
        ('user', '0014_alter_userreccomendationinfo_physical_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecommendation',
            name='no_rec_sport',
            field=models.ManyToManyField(to='base.sporttypeсontraindication', verbose_name='Рекомендации по противопоказанным видам спорта'),
        ),
    ]
