# Generated by Django 4.0.7 on 2022-10-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_userrecommendation_no_rec_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Код-подтверждения'),
        ),
    ]
