# Generated by Django 4.0.7 on 2022-10-06 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_user_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreccomendationinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_recomendation_info', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
