# Generated by Django 4.0.7 on 2022-10-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_userreccomendationinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_notification',
            field=models.ManyToManyField(related_name='user_notifications', to='user.usernotification', verbose_name='Пуш-уведомления'),
        ),
    ]
