# Generated by Django 4.0.7 on 2022-10-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_notificationtype'),
        ('user', '0018_alter_user_user_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='base.notificationtype', verbose_name='Тип уведомления'),
        ),
    ]
