# Generated by Django 4.0.7 on 2022-10-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_usernotification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreccomendationinfo',
            name='sport_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип спорта'),
        ),
        migrations.AddField(
            model_name='userreccomendationinfo',
            name='training_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип тренировки'),
        ),
    ]
