# Generated by Django 4.0.7 on 2022-10-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_breakfasteattype_dinnereattype_luncheattype'),
        ('user', '0020_userreccomendationinfo_sport_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecommendation',
            name='breakfast',
            field=models.ManyToManyField(to='base.breakfasteattype', verbose_name='Рекомендации по питанию (Завтрак)'),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='dinner',
            field=models.ManyToManyField(to='base.dinnereattype', verbose_name='Рекомендации по питанию (Ужин)'),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='lunch',
            field=models.ManyToManyField(to='base.luncheattype', verbose_name='Рекомендации по питанию (Обед)'),
        ),
    ]
