# Generated by Django 4.0.7 on 2022-10-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_userrecommendation_breakfast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recommendation',
            field=models.ManyToManyField(blank=True, to='user.userrecommendation', verbose_name='Мои Рекомендации'),
        ),
    ]
